"""Static mapping of HS Aalen study program abbreviations to full names."""

from __future__ import annotations


STUDY_PROGRAM_NAME_BY_CODE: dict[str, str] = {
    # Fakultaet Wirtschaftswissenschaften
    "B": "Betriebswirtschaft fuer kleine und mittlere Unternehmen",
    "BAN": "Business Analytics",
    "GM": "Gesundheitsmanagement",
    "I": "Internationale Betriebswirtschaft",
    "W": "Wirtschaftsingenieurwesen",
    "WI": "Wirtschaftsinformatik",
    "WIP": "Wirtschaftspsychologie",
    "DSB": "Data Science und Business Analytics berufsbegleitend",
    "IDM": "Industrial Management",
    "ISM": "IT-Sicherheitsmanagement berufsbegleitend",
    "MAG": "Master Auditing, Finance and Governance",
    "MF": "Financial Management",
    "MH": "Gesundheitsmanagement",
    "MI": "International Marketing and Sales",
    "MIM": "Master International Business (Schwerpunkt International Marketing and Sales)",
    "MM": "Mittelstandsmanagement",
    "MMM": "Master International Business (Schwerpunkt Mittelstandsmanagement)",
    "WIB": "Wirtschaftsinformatik berufsbegleitend",
    "WIC": "Wirtschaftsinformatik",
    # Fakultaet Optik und Mechatronik
    "A": "Augenoptik / Augenoptik und Hoerakustik",
    "AO": "Augenoptik / Optometrie",
    "DHM": "Digital Health Management",
    "F": "Mechatronik",
    "F - MEKA": "Mechatronik kompakt durch Anrechnung (Vorlesungsplan wie F)",
    "F - MEKA ET": "Mechatronik durch Anrechnung fuer Elektrotechniker (Vorlesungsplan wie F)",
    "FTC": "Technical Content Creation",
    "FTK": "Technische Redaktion",
    "FUX": "User Experience",
    "GBA": "Ingenieurpaedagogik",
    "HA": "Hoerakustik / Audiologie",
    "OE": "Optical Engineering",
    "APH": "Applied Photonics",
    "AOP": "Augenoptik und Psychophysik",
    "HTM": "Health Technology and Management",
    "MBD": "Business Development (Produktmanagement und Start-up-Management)",
    "MRM": "Mechatronik / Systems Engineering",
    "MTM PH": "Photonics",
    "VSB": "Vision Science and Business / Optometry",
    # Fakultaet Maschinenbau / Werkstofftechnik
    "K": "Kunststofftechnik",
    "M": "Allgemeiner Maschinenbau",
    "MBW": "Maschinenbau / Produktion und Management (Schwerpunkt Maschinenbau/Wirtschaft und Management)",
    "MBP": "Maschinenbau / Produktion und Management (Schwerpunkt Maschinenbau/Produktion und Management)",
    "MP": "Maschinenbau Plus",
    "P": "Maschinenbau / Produktentwicklung und Simulation",
    "PE": "Maschinenbau / Entwicklung: Design und Simulation",
    "VI": "International Sales Management and Technology",
    "VMG": "Oberflaechentechnologie / Neue Materialien (Schwerpunkt Materialographie / Neue Materialien)",
    "VMM": "Oberflaechentechnologie / Neue Materialien (Schwerpunkt Maschinenbau / Neue Materialien)",
    "VV": "Oberflaechentechnologie / Neue Materialien",
    "AMM": "Advanced Materials and Manufacturing",
    "IST": "Leadership in Industrial Sales and Technology",
    "LBM": "Leichtbau",
    "MDP": "Datenmanagement in Produktentwicklung und Produktion",
    "OMM": "Angewandte Oberflaechen- und Materialwissenschaften",
    "PEF": "Produktentwicklung und Fertigung",
    "PTC": "Polymer Technology",
    "TME": "Technologiemanagement (Schwerpunkt Entwicklung und Management)",
    "TMP": "Technologiemanagement (Schwerpunkt Produktion und Management)",
    # Fakultaet Chemie
    "C": "Chemie",
    "BPW": "Biopharmazeutische Wissenschaften",
    "ABC": "Analytische und Bioanalytische Chemie",
    # Fakultaet Elektronik und Informatik
    "DS": "Data Science",
    "ET": "Elektrotechnik",
    "ETI": "Technische Informatik / Embedded Systems",
    "ET - EKA": "Elektrotechnik kompakt durch Anrechnung (Vorlesungsplan wie ET)",
    "IN AI": "Informatik",
    "IN ITS": "Informatik (Schwerpunkt IT-Sicherheit)",
    "IN MI": "Informatik (Schwerpunkt Medieninformatik)",
    "IN SE": "Informatik (Schwerpunkt Software-Engineering)",
    "IOT": "Internet der Dinge",
    "DPD": "Digital Product Design and Development",
    "MIN": "Informatik",
    "MLD": "Machine Learning and Data Analytics",
    "MSD": "Advanced Systems Design (Systemtechnik)",
    # Sonstige
    "OS": "Orientierungssemester",
    "Z": "Kurse des Sprachenzentrums",
    "SST": "Schuelerstudium",
    "GLZ": "Grundlagenzentrum",
    "REK": "Rektorat",
    "VERW. SONSTIGE": "Verwaltungsmanagement / Besprechungen",
}
